//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class tbl_gender
{
    public int id { get; set; }
    public string gender { get; set; }
}

public partial class tbl_hobby
{
    public int id { get; set; }
    public string hobby { get; set; }
}

public partial class tbl_state
{
    public int id { get; set; }
    public string statename { get; set; }
}

public partial class tbl_subject
{
    public int id { get; set; }
    public string subject { get; set; }
}
